"""Fixing the default value for the create_date

Revision ID: 0d759008eeb3
Revises: 12ac227c9e85
Create Date: 2023-02-11 21:09:47.196685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d759008eeb3"
down_revision = "12ac227c9e85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charityproject", schema=None) as batch_op:
        batch_op.alter_column(
            "description", existing_type=sa.TEXT(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charityproject", schema=None) as batch_op:
        batch_op.alter_column(
            "description", existing_type=sa.TEXT(), nullable=False
        )

    # ### end Alembic commands ###
