"""Add user relationsip to Donation

Revision ID: 12ac227c9e85
Revises: c1763f68dd81
Create Date: 2023-02-09 14:40:01.736937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12ac227c9e85"
down_revision = "c1763f68dd81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_donation_user_id_user", "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donation", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_donation_user_id_user", type_="foreignkey"
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
